param()
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$root = Split-Path $PSScriptRoot -Parent
$ids  = @(Get-ChildItem (Join-Path $root "3d\glb") -Filter *.glb |
          Sort-Object Name | ForEach-Object { $_.BaseName })

$lines = @()
$lines += "// Generated by tools/make_cards.ps1 - do not edit by hand."
$lines += "const CARDS = ["
foreach ($id in $ids) { $lines += ('  "' + $id + '",') }
$lines += "];"

$out = Join-Path $root "cards.js"
[System.IO.File]::WriteAllLines($out, $lines, (New-Object System.Text.UTF8Encoding $false))
"wrote $out with $($ids.Count) ids"
